name: Deploy

on:
  repository_dispatch:
    types: deploy
    inputs:
      git-ref:
        description: Git ref to deploy (optional- defaults to master)
        required: false
      environment:
        description: Environment to deploy to (staging|production) (required)
        required: true
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git ref to deploy (optional- defaults to master)
        required: false
      environment:
        description: Environment to deploy to (staging|production) (required)
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout latest git-ref
       uses: actions/checkout@v2
       if: github.event.inputs.git-ref == ''
     - name: Checkout custom git-ref
       uses: actions/checkout@v2
       if: github.event.inputs.git-ref != ''
       with:
         ref: ${{ github.event.inputs.git-ref }}
     - name: Fake deploy script
       run: |
         REF=${{ github.event.inputs.git-ref != '' && github.event.inputs.git-ref || 'master' }}
         echo "Deploying $REF to ${{github.event.inputs.environment}}"
