name: Post to Slack

on:
  workflow_run:
    workflows: [Branch CI Run]
    types:
      - completed

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: post to slack
        run: |
          echo "github.event.workflow_run.html_url"
          echo ${{ github.event.workflow_run.html_url }}
          echo "github.event.workflow_run.head_sha"
          echo ${{ github.event.workflow_run.head_sha }}
          echo "github.event.workflow_run.event"
          echo ${{ github.event.workflow_run.event }}
