name: Post to Slack

on:
  workflow_run:
    workflows: [Branch CI Run]
    types:
      - completed

jobs:

  post:
    runs-on: ubuntu-latest
    steps:
      - name: Set Migration Text
        id: setMigrationText
        run: |
          echo "Setting pending migration message"
          LATEST_STR="2022-08-25T16:39:29+00:00"
          LATEST=`date -d "$LATEST_STR" +%s`
          TODAY=`date --utc +%s`
          SECS_P_DAY=86400
          DAYS_SINCE_LAST_MIGRATION=$((($TODAY - $LATEST)/$SECS_P_DAY ))
          echo ::set-output name=days_since_last_migration::$DAYS_SINCE_LAST_MIGRATION
      - name: post to slack
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "Days since last migration"
          echo ${{ steps.setMigrationText.outputs.days_since_last_migration }}
