name: Post to Slack

on:
  workflow_run:
    workflows: [Branch CI Run]
    types:
      - completed

jobs:

  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Migration Status
        id: fetchMigrationStatus
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://info-reader-sandbox.herokuapp.com/health_check
      - name: Set Migration Text
        id: setMigrationText
        run: |
          echo "Setting days since last migration"
          LATEST_STR=${{ fromJson(env.fetch-api-data).latest_migration_date }}
          echo "Latest migration string:"
          echo $LATEST_STR
          LATEST=`date -d "$LATEST_STR" +%s`
          echo "latest parsed"
          echo $LATEST
          TODAY=`date --utc +%s`
          echo "today parsed"
          echo $TODAY
          SECS_P_DAY=86400
          DAYS_SINCE_LAST_MIGRATION=$((($TODAY - $LATEST)/$SECS_P_DAY ))
          echo "test"
          echo $DAYS_SINCE_LAST_MIGRATION
          echo "after test"
          echo ::set-output name=days_since_last_migration::$DAYS_SINCE_LAST_MIGRATION
          echo "Setting shortened github SHA"
          SHA_SHORT=`echo ${{ github.event.workflow_run.head_sha }} | cut -c1-8`
          echo ::set-output name=sha_short::$SHA_SHORT
          echo "Shortened sha"
          echo $SHA_SHORT
          echo "setting short commit message"
          echo "message-"
          MESSAGE="${{ github.event.workflow_run.head_commit.message }}"
          echo $MESSAGE
          echo "-message"
          #MESSAGE=`echo ${{ github.event.workflow_run.head_commit.message }} | head -1`
          #echo $MESSAGE
          #echo ::set-output name=head_commit_message::$MESSAGE

      - name: post to slack
        run: |
          echo "Days since last migration"
          echo ${{ steps.setMigrationText.outputs.days_since_last_migration }}
          echo "Short SHA"
          echo ${{ steps.setMigrationText.outputs.sha_short }}
