name: Post to Slack

on:
  workflow_run:
    workflows: [Branch CI Run]
    types:
      - completed

jobs:
  post:
    runs-on: ubuntu-latest
    outputs:
      display_title: ${{ steps.setMigrationText.outputs.display_title }}
    steps:
      - name: Fetch Migration Status
        id: fetchMigrationStatus
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://info-reader-sandbox.herokuapp.com/health_check
      - name: Set Migration Text
        id: setMigrationText
        run: |
          echo "Setting days since last migration"
          LATEST_STR=${{ fromJson(env.fetch-api-data).latest_migration_date }}
          echo "Latest migration string:"
          echo $LATEST_STR
          LATEST=`date -d "$LATEST_STR" +%s`
          echo "latest parsed"
          echo $LATEST
          TODAY=`date --utc +%s`
          echo "today parsed"
          echo $TODAY
          SECS_P_DAY=86400
          DAYS_SINCE_LAST_MIGRATION=$((($TODAY - $LATEST)/$SECS_P_DAY ))
          echo "test"
          echo $DAYS_SINCE_LAST_MIGRATION
          echo "after test"
          echo ::set-output name=days_since_last_migration::$DAYS_SINCE_LAST_MIGRATION
          echo "Setting shortened github SHA"
          SHA_SHORT=`echo ${{ github.event.workflow_run.head_sha }} | cut -c1-8`
          echo ::set-output name=sha_short::$SHA_SHORT
          echo "Shortened sha"
          echo $SHA_SHORT
          echo "setting short commit message"
          echo ::set-output name=head_commit_message::${{ github.event.workflow_run.display_title }}

      - name: Dump github context
        run: |
          echo "Dumping context for inspection"
          echo "${{toJSON(github.event)}}"

      - name: post to slack
        run: |
          echo "Days since last migration"
          echo ${{ steps.setMigrationText.outputs.days_since_last_migration }}
          echo "Short SHA"
          echo ${{ steps.setMigrationText.outputs.sha_short }}

  another_job:
    runs-on: ubuntu-latest
    needs: post
    steps:
      - name: Use output from previous job
        run: |
          echo "Accessing var from previous job"
          echo ${{ needs.post.outputs.display_title }}
          echo "after"
